../linux-x86_64/Patch ../linux-x86_64/Diff:bzip2/blocksort.c bzip2/bzip2.c bzip2/bzip2recover.c bzip2/bzlib.c bzip2/compress.c  bzip2/crctable.c bzip2/decompress.c bzip2/huffman.c bzip2/randtable.c com_yyh_lib_bsdiff_PatchUtils.c com_yyh_lib_bsdiff_DiffUtils.c
	gcc bzip2/blocksort.c bzip2/bzip2.c bzip2/bzip2recover.c bzip2/bzlib.c bzip2/compress.c  bzip2/crctable.c bzip2/decompress.c bzip2/huffman.c bzip2/randtable.c com_yyh_lib_bsdiff_PatchUtils.c -o ../linux-x86_64/Patch
	gcc bzip2/blocksort.c bzip2/bzip2.c bzip2/bzip2recover.c bzip2/bzlib.c bzip2/compress.c  bzip2/crctable.c bzip2/decompress.c bzip2/huffman.c bzip2/randtable.c com_yyh_lib_bsdiff_DiffUtils.c -o ../linux-x86_64/Diff

.PHONY: edit clean
clean:
	rm ../linux-x86_64/Diff ../linux-x86_64/Patch