/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yyh_lib_bsdiff_JPatch */

#ifndef _Included_com_yyh_lib_bsdiff_JPatch
#define _Included_com_yyh_lib_bsdiff_JPatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yyh_lib_bsdiff_PatchUtils
 * Method:    genNewApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yyh_lib_bsdiff_PatchUtils_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
